replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-min/fruit@sha256:0f49e448f88c448e63dcd162909f3b83f08dd59577a6eccc7fd8c72fa9301ead # written by ploigos-step-runner
