replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-min/fruit@sha256:00cb8047e373814d2084d38d200ee29c66f4a5dbd102ea969e72d26a9eea9a21 # written by ploigos-step-runner
