replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-min/fruit@sha256:b2ac8acbaca9ea801a9a2df17dcc6eff57dca4a4ef0800b0cc2cf8d1a58b9cf1 # written by ploigos-step-runner
