replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-min/fruit@sha256:7ebaae689a21c741856781bc097015ce5d42960cfbe58651c0edb85561df3d06 # written by ploigos-step-runner
