replicaCount: 2
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-min/fruit@sha256:ca5147acfbcec9aff34a452a5780e93a3d941e877bcd2971c31a24a42b39e5ae # written by ploigos-step-runner
route:
  hostname: fruit-jenkins-min.prod.apps.tssc.rht-set.com
