replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-min/fruit@sha256:b9a5fffcec93b05d248a0f0d40addfab86c4f7eca8f6c51ffeceb1016473d847 # written by ploigos-step-runner
