apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    managed-admin/subject.name: system:serviceaccounts:openshift-gitops
    managed-admin/subject.kind: Group

