apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.fullname" . }}
  namespace: {{ .Values.deploymentNamespace }}
  labels:
    app: {{ template "application.name" . }}
    chart: {{ template "application.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "application.name" . }}
    release: {{ .Release.Name }}
